apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  tracing:
    samplingRate: "1"
    # Using OTLP for OpenTelemetry integration
    otel:
      endpointAddress: "localhost:4318"
      isSecure: false
      protocol: http
  metric:
    enabled: true
